stages:
  - validate
  - test
  - release
  - deploy
  - web_deploy

.puppet_def: &puppet_job_def
  stage: test
  script:
    - gem update --system > /dev/null
    - gem install bundler > /dev/null
    - bundle install --without development validate
    - bundle exec puppet module install puppetlabs-stdlib
    - bundle exec rake spec
  tags:
    - ruby

web_trigger_staging:
  type: web_deploy
  variables:
    REF: staging
  only:
    - master
  script:
    - "curl -X POST -F token=$PREPL_BUILD_TRIGGER_TOKEN -F ref=$REF https://gitlab.com/api/v3/projects/1146764/trigger/builds"

rubocop_ruby:
  stage: validate
  allow_failure: true
  only:
    - branches
  tags:
    - ruby
  script:
    - bundle install
    - bundle exec rubocop -D

bump_and_tag:
  type: release
  when: manual
  tags:
    - ruby2.2
  only:
    - master@puppet-debugger/puppet-debugger
  script:
    - gem install release_me 
    - bump_and_tag

#web_trigger_production:
#  type: web_deploy
#  variables:
#    REF: production
#  only:
#    - tags
#  tags:
#    - ruby
#  script:
#    - "curl -X POST -F token=$PREPL_BUILD_TRIGGER_TOKEN -F ref=$REF https://gitlab.com/api/v3/projects/1146764/trigger/builds"

.ruby_193: &ruby193
  image: ruby:1.9.3

.ruby_20: &ruby20
  image: ruby:2.0

.ruby_21: &ruby21
  image: ruby:2.1

.ruby_22: &ruby22
  image: ruby:2.2

.ruby_23: &ruby23
  image: ruby:2.3

.ruby_24: &ruby24
  image: ruby:2.4

gem_production:
  image: ruby:2.1
  tags:
    - ruby
  before_script:
    - gem install dpl
  stage: deploy
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tags

puppet_38_ruby193:
  variables:
    PUPPET_GEM_VERSION: "~> 3.8.0"
  <<: *puppet_job_def
  <<: *ruby193

puppet_38_ruby20:
  variables:
    PUPPET_GEM_VERSION: "~> 3.8.0"
  <<: *puppet_job_def
  <<: *ruby20

puppet_38_ruby21:
  variables:
    PUPPET_GEM_VERSION: "~> 3.8.0"
  <<: *puppet_job_def
  <<: *ruby21

puppet_43_ruby20:
  variables:
    PUPPET_GEM_VERSION: "~> 4.3.0"
  <<: *puppet_job_def
  <<: *ruby20

puppet_43_ruby21:
  variables:
    PUPPET_GEM_VERSION: "~> 4.3.0"
  <<: *puppet_job_def
  <<: *ruby21

puppet_43_ruby22:
  variables:
    PUPPET_GEM_VERSION: "~> 4.3.0"
  <<: *puppet_job_def
  <<: *ruby22

puppet_44_ruby21:
  variables:
    PUPPET_GEM_VERSION: "~> 4.4.0"
  <<: *puppet_job_def
  <<: *ruby21

puppet_44_ruby22:
  variables:
    PUPPET_GEM_VERSION: "~> 4.4.0"
  <<: *puppet_job_def
  <<: *ruby22

puppet_45_ruby21:
  variables:
    PUPPET_GEM_VERSION: "~> 4.5.0"
  <<: *puppet_job_def
  <<: *ruby21

puppet_46_ruby22:
  variables:
    PUPPET_GEM_VERSION: "~> 4.6.0"
  <<: *puppet_job_def
  <<: *ruby22

puppet_47_ruby22:
  variables:
    PUPPET_GEM_VERSION: "~> 4.7.0"
  <<: *puppet_job_def
  <<: *ruby22

puppet_410_ruby24:
  variables:
    PUPPET_GEM_VERSION: "~> 4.10.0"
  <<: *puppet_job_def
  <<: *ruby24

puppet_50_ruby24:
  variables:
    PUPPET_GEM_VERSION: "~> 5.0"
  <<: *puppet_job_def
  <<: *ruby24

puppet_51_ruby24:
  variables:
    PUPPET_GEM_VERSION: "~> 5.1"
  <<: *puppet_job_def
  <<: *ruby24

puppet_52_ruby24:
  variables:
    PUPPET_GEM_VERSION: "~> 5.2"
  <<: *puppet_job_def
  <<: *ruby24

puppet_53_ruby24:
  variables:
    PUPPET_GEM_VERSION: "~> 5.3"
  <<: *puppet_job_def
  <<: *ruby24