stages:
  - test
  - deploy
  - web_deploy

.puppet_def: &puppet_job_def
  stage: test
  script:
    - bundle install --without development
    - bundle exec puppet module install puppetlabs-stdlib
    - bundle exec rake spec

web_trigger:
  type: web_deploy
  script:
    - "curl -X POST -F token=PREPL_BUILD_TRIGGER_TOKEN -F ref=master https://gitlab.com/api/v3/projects/1146764/trigger/builds"

.ruby_193: &ruby193
  image: ruby:1.9.3

.ruby_20: &ruby20
  image: ruby:2.0

.ruby_21: &ruby21
  image: ruby:2.1

.ruby_22: &ruby22
  image: ruby:2.2

.ruby_23: &ruby23
  image: ruby:2.3

gem_production:
  image: ruby:2.1
  before_script:
    - gem install dpl
  stage: deploy
  script:
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  only:
    - tags

puppet_38_ruby193:
  variables:
    PUPPET_GEM_VERSION: '3.8'
  <<: *puppet_job_def
  <<: *ruby193

puppet_38_ruby20:
  variables:
    PUPPET_GEM_VERSION: '3.8'
  <<: *puppet_job_def
  <<: *ruby20

puppet_38_ruby21:
  variables:
    PUPPET_GEM_VERSION: '3.8'
  <<: *puppet_job_def
  <<: *ruby21

puppet_43_ruby20:
  variables:
    PUPPET_GEM_VERSION: '4.4'
  <<: *puppet_job_def
  <<: *ruby20

puppet_43_ruby21:
  variables:
    PUPPET_GEM_VERSION: '4.4'
  <<: *puppet_job_def
  <<: *ruby21

puppet_43_ruby22:
  variables:
    PUPPET_GEM_VERSION: '4.4'
  <<: *puppet_job_def
  <<: *ruby22

puppet_44_ruby21:
  variables:
    PUPPET_GEM_VERSION: '4.4'
  <<: *puppet_job_def
  <<: *ruby21

puppet_44_ruby22:
  variables:
    PUPPET_GEM_VERSION: '4.4'
  <<: *puppet_job_def
  <<: *ruby22

puppet_45_ruby21:
  variables:
    PUPPET_GEM_VERSION: '4.5'
  <<: *puppet_job_def
  <<: *ruby21

puppet_45_ruby22:
  variables:
    PUPPET_GEM_VERSION: '4.5'
  <<: *puppet_job_def
  <<: *ruby22
