language: ruby
cache: bundler
install: "bundle install --without development"
before_script: "bundle exec puppet module install puppetlabs-stdlib"
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.1
  - 2.1.3
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.8"
    - PUPPET_GEM_VERSION="~> 4.2"
    - PUPPET_GEM_VERSION="~> 4.3"
    - PUPPET_GEM_VERSION="~> 4.4"
notifications:
  email: corey@logicminds.biz

matrix:
  exclude:
    - rvm: 2.2.1
      env: PUPPET_GEM_VERSION="~> 3.8"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.4"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.3"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 4.2"    
